FROM openjdk:8-jre-alpine

RUN /usr/bin/java -version

COPY agent/target/ffwd-agent-0.0.1-SNAPSHOT.jar /ffwd-agent.jar
COPY docker/ffwd-shim.yaml /ffwd.yaml

ENTRYPOINT /usr/bin/java -cp /ffwd-agent.jar com.spotify.ffwd.FastForwardAgent
